/**
 * Animate for slide.
 */
module.exports = {
  bounce: { in: 'bounce', out: 'fadeOut' },
  flash: { in: 'flash', out: 'fadeOut' },
  rubberBand: { in: 'rubberBand', out: 'fadeOut' },
  shake: {in: 'shake', out: 'fadeOut'},
  headShake: {in: 'headShake', out: 'fadeOut'},
  swing: {in: 'swing', out: 'fadeOut'},
  tada: {in: 'tada', out: 'fadeOut'},
  wobble: {in: 'wobble', out: 'fadeOut'},
  jello: {in: 'jello', out: 'fadeOut'},
  bounceInOut: {in: 'bounceIn', out: 'bounceOut'},
  bounceInOutDown: {in: 'bounceInDown', out: 'bounceOutDown'},
  bounceInOutLeft: {in: 'bounceInLeft', out: 'bounceOutRight'},
  bounceInOutRight: {in: 'bounceInRight', out: 'bounceOutLeft'},
  bounceInOutUp: {in: 'bounceInUp', out: 'bounceOutUp'},
  fadeInOut: {in: 'fadeIn', out: 'fadeOut'},
  fadeInOutDown: {in: 'fadeInDown', out: 'fadeOutDown'},
  fadeInOutDownBig: {in: 'fadeInDownBig', out: 'fadeOutDownBig'},
  fadeInOutLeft: {in: 'fadeInLeft', out: 'fadeOutRight'},
  fadeInOutLeftBig: {in: 'fadeInLeftBig', out: 'fadeOutRightBig'},
  fadeInOutRight: {in: 'fadeInRight', out: 'fadeOutLeft'},
  fadeInOutRightBig: {in: 'fadeInRightBig', out: 'fadeOutLeftBig'},
  fadeInOutUp: {in: 'fadeInUp', out: 'fadeOutUp'},
  fadeInOutUpBig: {in: 'fadeInUpBig', out: 'fadeOutUpBig'},
  flipInOutX: {in: 'flipInX', out: 'flipOutX'},
  flipInOutY: {in: 'flipInY', out: 'flipOutY'},
  lightSpeedInOut: {in: 'lightSpeedIn', out: 'lightSpeedOut'},
  rotateInOut: {in: 'rotateIn', out: 'rotateOut'},
  rotateInOutDownLeft: {in: 'rotateInDownLeft', out: 'rotateOutDownLeft'},
  rotateInOutDownRight: {in: 'rotateInDownRight', out: 'rotateOutDownRight'},
  rotateInOutUpLeft: {in: 'rotateInUpLeft', out: 'rotateOutUpLeft'},
  rotateInOutUpRight: {in: 'rotateInUpRight', out: 'rotateOutUpRight'},
  hinge: {in: 'fadeIn', out: 'hinge'},
  rollInOut: {in: 'rollIn', out: 'rollOut'},
  zoomInOut: {in: 'zoomIn', out: 'zoomOut'},
  zoomInOutDown: {in: 'zoomInDown', out: 'zoomOutDown'},
  zoomInOutLeft: {in: 'zoomInLeft', out: 'zoomOutLeft'},
  zoomInOutRight: {in: 'zoomInRight', out: 'zoomOutRight'},
  zoomInOutUp: {in: 'zoomInUp', out: 'zoomOutUp'},
  slideInOutDown: {in: 'slideInDown', out: 'slideOutDown'},
  slideInOutLeft: {in: 'slideInLeft', out: 'slideOutRight'},
  slideInOutRight: {in: 'slideInRight', out: 'slideOutLeft'},
  slideInOutUp: {in: 'slideInUp', out: 'slideOutUp'}
}
