/**
 * Animate for slide.
 */
module.exports = {
  flash: { in: 'flash', out: 'fadeOut' },
  rubberBand: { in: 'rubberBand', out: 'fadeOut' },
  shake: {in: 'shake', out: 'fadeOut'},
  headShake: {in: 'headShake', out: 'fadeOut'},
  swing: {in: 'swing', out: 'fadeOut'},
  tada: {in: 'tada', out: 'fadeOut'},
  wobble: {in: 'wobble', out: 'fadeOut'},
  jello: {in: 'jello', out: 'fadeOut'},
  bounce: {in: 'bounceIn', out: 'bounceOut'},
  bounceDown: {in: 'bounceInDown', out: 'bounceOutDown'},
  bounceLeft: {in: 'bounceInLeft', out: 'bounceOutRight'},
  bounceRight: {in: 'bounceInRight', out: 'bounceOutLeft'},
  bounceUp: {in: 'bounceInUp', out: 'bounceOutUp'},
  fade: {in: 'fadeIn', out: 'fadeOut'},
  fadeDown: {in: 'fadeInDown', out: 'fadeOutDown'},
  fadeDownBig: {in: 'fadeInDownBig', out: 'fadeOutDownBig'},
  fadeLeft: {in: 'fadeInLeft', out: 'fadeOutRight'},
  fadeLeftBig: {in: 'fadeInLeftBig', out: 'fadeOutRightBig'},
  fadeRight: {in: 'fadeInRight', out: 'fadeOutLeft'},
  fadeRightBig: {in: 'fadeInRightBig', out: 'fadeOutLeftBig'},
  fadeUp: {in: 'fadeInUp', out: 'fadeOutUp'},
  fadeUpBig: {in: 'fadeInUpBig', out: 'fadeOutUpBig'},
  flipX: {in: 'flipInX', out: 'flipOutX'},
  flipY: {in: 'flipInY', out: 'flipOutY'},
  lightSpeed: {in: 'lightSpeedIn', out: 'lightSpeedOut'},
  rotate: {in: 'rotateIn', out: 'rotateOut'},
  rotateDownLeft: {in: 'rotateInDownLeft', out: 'rotateOutDownLeft'},
  rotateDownRight: {in: 'rotateInDownRight', out: 'rotateOutDownRight'},
  rotateUpLeft: {in: 'rotateInUpLeft', out: 'rotateOutUpLeft'},
  rotateUpRight: {in: 'rotateInUpRight', out: 'rotateOutUpRight'},
  hinge: {in: 'fadeIn', out: 'hinge'},
  roll: {in: 'rollIn', out: 'rollOut'},
  zoom: {in: 'zoomIn', out: 'zoomOut'},
  zoomDown: {in: 'zoomInDown', out: 'zoomOutDown'},
  zoomLeft: {in: 'zoomInLeft', out: 'zoomOutLeft'},
  zoomRight: {in: 'zoomInRight', out: 'zoomOutRight'},
  zoomUp: {in: 'zoomInUp', out: 'zoomOutUp'},
  slideDown: {in: 'slideInDown', out: 'slideOutDown'},
  slideLeft: {in: 'slideInLeft', out: 'slideOutRight'},
  slideRight: {in: 'slideInRight', out: 'slideOutLeft'},
  slideUp: {in: 'slideInUp', out: 'slideOutUp'}
}
